services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: |
      curl -LsSf https://astral.sh/uv/install.sh | sh && \
      export PATH="$HOME/.cargo/bin:$PATH" && \
      uv pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PATH
        value: /opt/render/project/.cargo/bin:$PATH
    healthCheckPath: /api/health
